version: '3'
services:
  python3:
    restart: always
    build: .
    container_name: 'python3_flask'
    working_dir: '/root/Flask/'
    tty: true
    volumes:
      - ./Flask:/root/Flask
    ports:
      - 5000:5000
    environment:
      FLASK_ENV: "production"
      PORTS: '5000'
    command: "flask run --host 0.0.0.0 --port 5000"
